platform:
  - x64
environment:
  RUST_INSTALL_DIR: C:\Rust
  matrix:
    - RUST_INSTALL_TRIPLE: i686-pc-windows-gnu
    - RUST_INSTALL_TRIPLE: x86_64-pc-windows-gnu

install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-1.0.0-beta-$Env:RUST_INSTALL_TRIPLE.exe"
  - cmd: rust-1.0.0-beta-%RUST_INSTALL_TRIPLE%.exe /VERYSILENT /NORESTART /COMPONENTS="rust,gcc,cargo" /DIR="%RUST_INSTALL_DIR%"
  - cmd: SET PATH=%PATH%;%RUST_INSTALL_DIR%\bin;
  - rustc -V
  - cargo -V
  - cinst 7zip.commandline -x86
  - ps: if($env:RUST_INSTALL_TRIPLE -eq 'x86_64-pc-windows-gnu') {
         Start-FileDownload "http://libgd.blob.core.windows.net/mingw/mingw-w64-dgn-x86_64-20141001.7z";
         7z x -oC:\ mingw-w64-dgn-x86_64-20141001.7z;
         Start-FileDownload "https://gitlab.com/Fraser999/Dependencies/raw/master/bin/x86_64-pc-windows-gnu/libsqlite3.a";        
          mkdir .\bin\x86_64-pc-windows-gnu;
          move .\libsqlite3.a .\bin\x86_64-pc-windows-gnu;
       }
  - ps: if($env:RUST_INSTALL_TRIPLE -eq 'i686-pc-windows-gnu') {
          Start-FileDownload "https://gitlab.com/Fraser999/Dependencies/raw/master/bin/i686-pc-windows-gnu/libsqlite3.a";
          mkdir .\bin\i686-pc-windows-gnu;
          move .\libsqlite3.a .\bin\i686-pc-windows-gnu\;
        }
  - if "%RUST_INSTALL_TRIPLE%" == "i686-pc-windows-gnu" SET PATH=%PATH%;C:\MinGW\bin;
  - if "%RUST_INSTALL_TRIPLE%" == "x86_64-pc-windows-gnu" SET PATH=%PATH%;C:\mingw64\bin;
  - ps: Start-FileDownload 'https://download.libsodium.org/libsodium/releases/libsodium-1.0.2-mingw.tar.gz'
  - 7z e libsodium-1.0.2-mingw.tar.gz && 7z x libsodium-1.0.2-mingw.tar -olibsodium -y
  - if "%RUST_INSTALL_TRIPLE%" == "i686-pc-windows-gnu" mkdir bin\i686-pc-windows-gnu && copy libsodium\libsodium-win32\lib\libsodium.a bin\i686-pc-windows-gnu\ && SET PATH=C:\MinGW\bin;%PATH%
  - if "%RUST_INSTALL_TRIPLE%" == "x86_64-pc-windows-gnu" mkdir bin\x86_64-pc-windows-gnu && copy libsodium\libsodium-win64\lib\libsodium.a bin\x86_64-pc-windows-gnu\ && SET PATH=C:\mingw64\bin;%PATH%

build: false

test_script:
  - cargo test --verbose
  - cargo test --verbose 
