install:
  - ps: |
        Start-FileDownload "https://github.com/maidsafe/QA/raw/master/Powershell%20Scripts/InstallRust.ps1"; . .\InstallRust.ps1
        if($env:platform -eq 'x86') {
          $env:Path = $env:Path + ";C:\MinGW\bin";
        } else {
          Start-FileDownload "http://libgd.blob.core.windows.net/mingw/mingw-w64-dgn-x86_64-20141001.7z";
          7z x -oC:\ mingw-w64-dgn-x86_64-20141001.7z | findstr /b /c:"Everything is Ok";
          $env:Path = $env:Path + ";C:\MinGW64\bin";
        }
        Start-FileDownload "https://github.com/maidsafe/QA/raw/master/Dependencies/Windows/$env:platform/libsodium.a";
        $env:SODIUM_LIB_DIR = Resolve-Path .

platform:
  - x86
  - x64

configuration:
#  - Debug
  - Release

environment:
  matrix:
#    - RUST_VERSION: 1.1.0
#    - RUST_VERSION: beta
    - RUST_VERSION: nightly

build: false

test_script:
  - ps: if ($env:CONFIGURATION -eq "Release") {
          $env:config_flags = "--release"
        }
  - cargo build --verbose %config_flags%
  - cargo test --verbose
